### ISSUE TITLE
Is there any step by step teaching?

### ISSUE THREAD

**Issue by choicky** [hiproz/hugo-sync#1]
hugo-sync is a good idear.  However, I still don't know how to deploy it.

**Comment by hiproz** [comment]
please confirm the "how to use"and "work flow" section, and tell me  the detail of the issue,

**Comment by choicky** [comment]
我就直接在你这里回复了，见--开头的部分：

`work flow`与`how to use`都有一些困惑。请教一下。

先说背景，假设我通过`hugo new site example.com` 创建了一个网站在我目录下。

## 关于 `work flow`
> 1. set the github hook event.

这个repo是用来存放 example.com 还是只是存放其中的`content`文件夹？
这个payload URL是hugo-sync server的地址吧？怎么填呢？
--存放的是content，content里面是全部网站的内容，所有有手动的内容。其中post里面存放的是wordpress生成的markdown文件，外面的几个是手动添加的。具体的布局要看你网站的页面关系
payload：yourdomaim.com/xyz .  通过nignx 识别 xyz来做url的转发，转发到对应的python server。

> 3. deploy your hook server in your wordpress server and hugo server if necessary.

这个deploy是指`/xx/xxx/python3 /xx/xx/wp-hook-svr.py`吗？
--是的，wordpress 只是访问一个 url，这个url通过nginx转发后，给到  wp-hook-svr, 然后wp-hook-svr就可以调用本地脚本完成相应的工作

>4. write in your wodpress page or in the github. the github will send webservice hook event to our hook server.

这里是指，步骤1的repo文件更新之后，就能通知 hugo-sync server吧？
--不管你是在wordpress发表文章还是在repo中手动添加markdown文件，都会触发hugo-sync server

>5. the hugo hook server will update the hugo content and start the hugo procedural after received the github hook event msg . 6. after the finish of hugo converting, the static html page will be in public folder of hugo.

这里是指hugo-sync能把文件从步骤1的repo pull下来，然后自动生成静态文件吧？
--是的，生成html

>6. the hugo hook server deploy the html to our website .

步骤5已经在public生成了静态文件；步骤6的deploy是指啥？
--把在hugo生成目录下的文件，copy到你的web server的可访问目录下（我的hugo只是用来生成网站，真正的网站是部署在nginx下的），如果你的网站不是这样的，这一步可以自行调整。

## 关于`how to use`
> 3. clone the repo, and deploy the folder in your hugo website root dictionary.

这个repo 是指hugo-sync的repo吧？
--yes

> 4. colne the markdown repo of your hugo website, and deploy the folder in your hugo website root dictionary.

这个步骤中，markdown repo 与`work flow`步骤1 repo是同一个吗？因为要放在example.com根目录，所以这个repo只是保存`content`? 我觉得整个example.com 都保存会更好吧？
--是同一个。是 content, content 里面存放的是整个目标目录的内容，这个你结合前面的回答理解下。 因为你所谓的example.com 是hugo的框架和模版，真正的目标网站内容其实只有 content。所以只要管理conten就可以。hugo可从官方自行升级。模版也最好单独管理，比如我的另一个 repo ：hyde-z
